env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres